export const projects = [
  {
    id: "indian-sacred-roots",
    title: "Indian Sacred\nRoots",
    description: "A comprehensive digital platform dedicated to the spiritual heritage and temples of India.",
    year: "2026",
    tech: ["Web Dev", "UI/UX", "Database"],
    image: "/images/projects/templex.png",
    link: "https://www.indiansacredroots.com/",
  },
  {
    id: "ark-kidoid",
    title: "ARK Kidoid | MKP",
    description: "A dedicated application and website built for Masti Ki Paathshaala, teaching new skills in a joyful environment.",
    year: "2026",
    tech: ["Product Design", "UI/UX", "App Dev", "Web Dev"],
    image: "/images/projects/mkpx.png",
    link: "https://www.mastikipaathshaala.org/",
  },
  {
    id: "mr-bites",
    title: "MR BITES",
    description: "Campus food ordering platform redefining student dining experiences and eliminating wait times.",
    year: "2026",
    tech: ["Product Strategy", "UI/UX", "Mobile App"],
    image: "/images/projects/mrbitesx.png",
    link: "https://www.mrbites.in/",
  },
  {
    id: "presnag",
    title: "PreSnag",
    description: "Restaurant SaaS ordering platform reimagining digital ordering and order management.",
    year: "2026",
    tech: ["Product Design", "Web Dev", "Backend"],
    image: "/images/projects/presnag2.png",
    link: "https://presnag.com",
  },
  {
    id: "miyaabi",
    title: "Miyaabi",
    description: "A modern fashion commerce platform for a contemporary clothing brand with immersive storytelling.",
    year: "2026",
    tech: ["Brand Identity", "E-Commerce", "UI/UX"],
    image: "/images/projects/miyaabix2.png",
    link: "https://miyaabi.vercel.app/",
  },
  {
    id: "geoenergys",
    title: "GeoEnergys",
    description: "An interactive energy intelligence platform that turns global energy trade into explorable data.",
    year: "2026",
    tech: ["Data Viz", "Frontend", "UI/UX"],
    image: "/images/projects/GeoEnergys.png",
    link: "https://geo-energys.vercel.app/",
  }
];
